name: "IvInfo"
guid: "abe0c619-a145-4890-896b-cb1089ade4fe"
imageUrl: "https://raw.githubusercontent.com/Su8Zer0/IvInfo/master/logo.png"
version: "0.1.7.5"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "SubZeroPL"
overview: "Idol video info metadata provider. Uses data from javlibrary.com, dmm.co.jp, gekiyasu.co.jp"
description: |
  Idol video info metadata provider.
  Uses data from javlibrary.com, dmm.co.jp, gekiyasu.co.jp.
  Fetches video metadata and cover/box/screenshot images.
  Also fetches trailers from DMM.

category: "Metadata"
artifacts:
  - "IvInfo.dll"
  - "F23.StringSimilarity.dll"
  - "AngleSharp.dll"
  - "AngleSharp.XPath.dll"
changelog: |
  fixed english cast and director scraping
