---
name: "IvInfo"
guid: "abe0c619-a145-4890-896b-cb1089ade4fe"
version: "0.1.5.6"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "SubZeroPL"
overview: "Idol video info metadata provider. Uses data from javlibrary.com, dmm.co.jp, gekiyasu.co.jp"
description: >
  Idol video info metadata provider. Uses data from javlibrary.com, dmm.co.jp, gekiyasu.co.jp

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.IvInfo.dll"
changelog: |-
  - added external ids
  - remade searching
  - merging of results from different scrapers
  - extended configuration page
  - moved configuration page js to separate file
  - dmm scraper currently not working (no proxy)
