---
name: "IvInfo"
guid: "abe0c619-a145-4890-896b-cb1089ade4fe"
version: "0.1.5.2"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "SubZeroPL"
overview: "Idol video info metadata provider. Uses data from javlibrary.com, dmm.co.jp, gekiyasu.co.jp"
description: >
  Idol video info metadata provider. Uses data from javlibrary.com, dmm.co.jp, gekiyasu.co.jp

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.IvInfo.dll"
changelog: |-
  - small fix for Javlibrary scraper user score parsing
