name: "IvInfo"
guid: "abe0c619-a145-4890-896b-cb1089ade4fe"
imageUrl: "https://raw.githubusercontent.com/Su8Zer0/IvInfo/master/logo.png"
version: "1.0.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "Su8Zer0"
overview: "Idol video info metadata provider. Uses data from javlibrary.com, dmm.co.jp, gekiyasu.co.jp"
description: |
  Idol video info metadata provider.
  Uses data from r18.dev, javlibrary.com, dmm.co.jp, gekiyasu.co.jp.
  Fetches video metadata and cover/box/screenshot images.
  Also fetches trailers from R18 and DMM.

category: "Metadata"
artifacts:
  - "IvInfo.dll"
  - "F23.StringSimilarity.dll"
  - "AngleSharp.dll"
  - "AngleSharp.XPath.dll"
  - "FlareSolverrSharp.dll"
changelog: |
  new jf version support,
  flaresolverr support for javlibrary.com
