name: Build new version

on:
  push:
    tags:
    - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Get version
      id: get_version
      run: echo "version=$((Select-Xml -Path .\Jellyfin.Plugin.IvInfo.csproj -XPath "/Project/PropertyGroup/AssemblyVersion").Node.InnerXML)" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: jprm-build
      uses: oddstr13/jellyfin-plugin-repository-manager@v1.0.11
      with:
        dotnet-target: net6.0
    - name: Upload zip artifact
      uses: actions/upload-artifact@v3
      with:
        name: ivinfo_${{ steps.get_version.outputs.version }}
        path: artifacts/ivinfo_${{ steps.get_version.outputs.version }}.zip
  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version
        id: get_version
        run: echo "version=$((Select-Xml -Path .\Jellyfin.Plugin.IvInfo.csproj -XPath "/Project/PropertyGroup/AssemblyVersion").Node.InnerXML)" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download build
        id: download_artifacts
        uses: actions/download-artifact@v3
        with:
          name: ivinfo_${{ steps.get_version.outputs.version }}
          path: release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Jellyfin.Plugin.IvInfo Release v${{ steps.get_version.outputs.version }}
          prerelease: false
          body: |
            ## Release
            Jellyfin.Plugin.IvInfo v${{ steps.get_version.outputs.version }}
            ## Changes
            ${{ steps.changelog.outputs.changes }}
      - name: Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/ivinfo_${{ steps.get_version.outputs.version }}.zip
          asset_name: Jellyfin.Plugin.IvInfo_${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip
      - name: Post release to repo
        id: post-to-repo
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1.5
        with:
          url: https://subzeropl.duckdns.org/jf-plugin-repo/release.php?id=${{ steps.create_release.outputs.id }}
          fail_fast: true
