name: Build new version

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
      debug_detached:
        type: boolean
        description: 'Run tmate session as detached'
        required: false
        default: false
      draft_release:
        type: boolean
        description: 'Create draft release'
        required: false
        default: false
      no_publish:
        type: boolean
        description: 'Don''t publish (no release, no manifest update, no upload to repo'
        required: false
        default: false
      skip_tests:
        type: boolean
        description: 'Skip unit tests step'
        required: false
        default: false

jobs:
  build:
    if: ((github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      PROJECT_NAME: IvInfo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.*
      - name: Install jprm
        run: pip install --user jprm
        shell: sh
      - name: Init repo
        run: |
          mkdir repo
          cp manifest.json repo/
        shell: sh
      - name: Build plugin
        run: jprm plugin build --output ./repo --dotnet-framework net6.0 .
        shell: sh
      - name: Run tests
        run: dotnet test --nologo -c Release -v normal --filter "Category!=GithubSkip"
        shell: pwsh
        if: ${{ !inputs.skip_tests }}
      - name: Get version
        id: get_version
        run: echo "version=$((Select-Xml -Path .\$( $env:PROJECT_NAME )\$( $env:PROJECT_NAME ).csproj -XPath '/Project/PropertyGroup/AssemblyVersion').Node.InnerXML)" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - name: Add to manifest
        run: jprm repo add --plugin-url https://github.com/${{ github.repository }}/releases/download/v${{ steps.get_version.outputs.version }}/ivinfo_${{ steps.get_version.outputs.version }}.zip ./repo ./repo/ivinfo_${{ steps.get_version.outputs.version }}.zip
        shell: sh
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Draft Release
        id: create_draft_release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.draft_release && !inputs.no_publish }}
        with:
          artifacts: repo/ivinfo_${{ steps.get_version.outputs.version }}.zip
          name: IvInfo Release v${{ steps.get_version.outputs.version }}
          tag: v${{ steps.get_version.outputs.version }}_pre
          commit: master
          prerelease: true
          draft: true
          body: |
            ${{ steps.changelog.outputs.changes }}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        if: ${{ !inputs.draft_release && !inputs.no_publish }}
        with:
          artifacts: repo/ivinfo_${{ steps.get_version.outputs.version }}.zip
          name: IvInfo Release v${{ steps.get_version.outputs.version }}
          tag: v${{ steps.get_version.outputs.version }}
          commit: master
          prerelease: false
          draft: false
          body: |
            ${{ steps.changelog.outputs.changes }}
      - name: Push updated manifest to git
        run: |
          git checkout master
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          mv ./repo/manifest.json ./
          git add manifest.json
          git commit -m "ci: updated manifest.json to version ${{ steps.get_version.outputs.version }}"
          git push
        shell: sh
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: ${{ inputs.debug_detached }}
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
